### ISSUE TITLE
Can you share the server side code? 

### ISSUE THREAD

**Issue by zgb7mtr** [punneetmehta/wapi_rest#1]
There are security concerns about signing on someone else's server.

**Comment by punneetmehta** [comment]
Mm, I won't be sharing server side code.
My Plan is to offer an Easy to use service and obviously to keep it away from spammers ( so sharing the code is not an option )

Coming to your Security Concern part, yes theoretically signing on someone else's server raises a security concern.
But **i can assure you**, no one else will be accessing your data or your api.
Moreover, I am implementing an API key based access, so that anyone with the phone number can't access the api directly.
